name: Gradle build

on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK version to use"
        required: true
        type: string
      java-distribution:
        description: "JDK distribution to use"
        required: false
        type: string
        default: "temurin"
      artifact-name:
        description: "Name of artifact to get"
        required: false
        type: string
        default: ""
      runs-on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Dependencies submission
    runs-on: [ "${{ inputs.runs-on }}" ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.3.0
        continue-on-error: true

  build:
    name: Gradle - Build
    runs-on: [ "${{ inputs.runs-on }}" ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0

      - name: Build project
        run: |
          ./gradlew \
          build

      - name: Upload artifacts
        id: gradle-build
        uses: actions/upload-artifact@v4.6.0
        if: "${{ inputs.artifact-name != '' }}"
        with:
          name: ${{ inputs.artifact-name }}
          path: build/libs/*.jar
          retention-days: 7
          if-no-files-found: warn
