name: Nodejs lint

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string
      pnpm-version:
        description: "PNPM version"
        required: true
        type: string
      runs-on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"
      environment:
        description: "Environment to use"
        required: false
        type: string

jobs:
  lint:
    name: Nodejs - Lint
    runs-on: [ "${{ inputs.runs-on }}" ]
    environment: ${{ inputs.environment }}
    concurrency:
      group: node-lint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v5.0.0
      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm lint
        continue-on-error: true
