name: Sync wiki

on:
  workflow_call:
    inputs:
      path:
        description: "Path of the wiki in the sources"
        required: true
        type: string
      only-default-branch:
        description: "Weather to run only on default branch"
        required: false
        type: boolean
        default: true
      runs-on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"
      environment:
        description: "Environment to use"
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Wiki - Sync
    runs-on: [ "${{ inputs.runs-on }}" ]
    environment: ${{ inputs.environment }}
    concurrency:
      group: wiki-sync-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v5.0.0
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Push changes to the wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5.0.1
        if: ${{ ! inputs.only-default-branch || (steps.get_release.outputs.target_commitish || github.ref_name) == format('{0}', github.event.repository.default_branch) }}
        with:
          path: ${{ inputs.path }}
