name: Sync wiki

on:
  workflow_call:
    inputs:
      path:
        description: "Path of the wiki in the sources"
        required: true
        type: string
      runs-on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: write

jobs:
  build:
    name: Wiki - Sync
    runs-on: [ "${{ inputs.runs-on }}" ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
      - name: Push changes to the wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4.4.0
        with:
          path: ${{ inputs.path }}
